name: picklebook-mailpit

networks:
  picklebook-network:
    external: true
    name: picklebook-network

services:
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    environment:
      MP_MAX_MESSAGES: 5000
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
      MP_LABEL: picklebook Test
    networks:
      - picklebook-network
    profiles: ["nonprod"]
